---
language: ruby

matrix:
  include:
  - os: linux
    rvm: 2.0
  - os: osx
    rvm: 2.0
  - os: linux
    rvm: 2.1
  - os: osx
    rvm: 2.1
  - os: linux
    rvm: 2.2.5
  - os: osx
    rvm: 2.2.5
  - os: linux
    rvm: 2.3.1
  - os: osx
    rvm: 2.3.1
  - os: linux
    rvm: 2.4.0
    env:
      - RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
  - os: osx
    rvm: 2.4.0
    env:
      - RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
  - os: linux
    rvm: ruby-head
    env:
      - RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
  - os: osx
    rvm: ruby-head
    env:
      - RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
  allow_failures:
  - rvm: ruby-head
  fast_finish: true

script:
  - bundle install
  - make
  - bundle exec rake test
